config/routes.rb
Rails.application.routes.draw do
  root "tweets#index"
  devise_for :users
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    resources :comments, except: [:index, :edit, :update]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :comments

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :favorites
  has_many :favorite_tweets, through: :favorites, source: :tweet
  has_many :comments
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    comment = current_user.comments.build(tweet_id: params[:tweet_id], body: comment_params[:body])
    comment.save
    redirect_to tweet_path(params[:tweet_id])
  end

  def show
    @comment = Comment.find(params[:id])
    @user = User.find(@comment.user_id)
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to tweet_path(comment.tweet_id)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.build(tweet_id: params[:tweet_id])
    favorite.save
    redirect_to tweets_path
  end

  def destroy
    favorite = Favorite.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    favorite.destroy
    redirect_to tweets_path
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to users_path
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def new
    @tweet = Tweet.new
  end

  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
    @user = @tweet.user
    @comments = Comment.where(tweet_id: params[:id])
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    @tweet.save
    redirect_to tweets_path
  end

  private
    def tweet_params
      params.require(:tweet).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    @favorite_tweets = @user.favorite_tweets
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.slim
h1 コメント作成

= form_with url: tweet_comments_path, model: [@tweet, @comment] do |f|
  div class="field"
    = f.label :body, "コメント内容"
    br
    = f.text_area :body
    br
    = f.submit

app/views/comments/show.html.slim
h1 コメント詳細

p
  span email:
  = link_to @user.email, user_path(@user.id)
p
  span コメント内容:
  = @comment.body
br

- if current_user.id == @user.id
  = link_to "削除", tweet_comment_path(@comment.id), method: :delete

app/views/favorites/create.html.slim
h1 Favorites#create
p Find me in app/views/favorites/create.html.slim

app/views/favorites/destroy.html.slim
h1 Favorites#destroy
p Find me in app/views/favorites/destroy.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | AssociationTutorial
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if user_signed_in?
      = link_to "新規投稿", new_tweet_path
      = link_to "ログアウト", destroy_user_session_path, method: :delete
      = link_to "マイページ", user_path(current_user.id)
    - else
      = link_to "新規登録", new_user_registration_path
      = link_to "ログイン", new_user_session_path
    = link_to "ツイート一覧", tweets_path
    = link_to "ユーザー一覧", users_path
    = yield

app/views/relationships/create.html.slim
h1 Relationships#create
p Find me in app/views/relationships/create.html.slim

app/views/relationships/destroy.html.slim
h1 Relationships#destroy
p Find me in app/views/relationships/destroy.html.slim

app/views/tweets/create.html.slim
h1
  | Tweets#create
p
  | Find me in app/views/tweets/create.html.erb

app/views/tweets/index.html.slim
h1
  | Tweets#index
p
  | Find me in app/views/tweets/index.html.erb

- @tweets.each do |tweet|
  hr
  p
    span email:
    = link_to tweet.user.email, user_path(tweet.user.id)
  p
    span ツイート内容:
    = link_to tweet.body, tweet_path(tweet.id)
  - if user_signed_in?
    - if tweet.favorited_by?(current_user)
      p
        span お気に入り解除:
        = link_to tweet.favorites.count, tweet_favorites_path(tweet.id), method: :delete
    - else
      p
        span お気に入り登録:
        = link_to tweet.favorites.count, tweet_favorites_path(tweet.id), method: :post
    - if current_user != tweet.user
      - if tweet.user.followed_by?(current_user)
        p
          = link_to "フォロー済み", user_relationships_path(tweet.user.id), method: :delete
      - else
        p
          = link_to "フォローする", user_relationships_path(tweet.user.id), method: :post
  - else
    p
      span お気に入り数:
      = tweet.favorites.count

app/views/tweets/new.html.slim
h1 Tweet#index
p Find me in app/views/tweets/new.html.slim

= form_for @tweet do |f|
  p
    = f.label :body, "ツイート"
    = f.text_field :body
  = f.submit

app/views/tweets/show.html.slim
h1
  | Tweets#show
p
  | Find me in app/views/tweets/show.html.erb

p
  span email:
  = @user.email
p
  span ツイート内容:
  = @tweet.body
= link_to "コメントする", new_tweet_comment_path(params[:id])

- @comments.each do |comment|
  hr
  p
    = comment.body
    br
    = link_to "詳細",tweet_comment_path(params[:id], comment.id)

app/views/users/followers.html.slim
h1 フォロワー一覧

- @users.each do |user|
  hr
  p
    span email:
    = link_to user.email, user_path(user.id)
  - if current_user != user
    - if user.followed_by(current_user)
      p = link_to "フォロー済み", user_relationships_path(user.id), method: :delete
    - else
      p = link_to "フォローする", user_relationships_path(user.id), method: :post

app/views/users/follows.html.slim
h1 フォロー一覧

- @users.each do |user|
  hr
  p
    span email:
    = link_to user.email, user_path(user.id)
  - if current_user != user
    - if user.followed_by?(current_user)
      p = link_to "フォロー済み", user_relationships_path(user.id), method: :delete
    - else
      p = link_to "フォローする", user_relationships_path(user.id), method: :post

app/views/users/index.html.slim
h1
  | Users#index
p
  | Find me in app/views/users/index.html.erb

- @users.each do |user|
  hr
  p
    span email:
    = link_to user.email, user_path(user.id)
    - if current_user != user
      - if user.followed_by?(current_user)
        p
          = link_to "フォロー済み", user_relationships_path(user.id), method: :delete
      - else
        p
          = link_to "フォローする", user_relationships_path(user.id), method: :post

app/views/users/show.html.slim
h1
  | Users#show
p
  | Find me in app/views/users/show.html.erb

hr
p
  span email:
  = @user.email

p = link_to "フォロー", follows_user_path(@user.id)
p = link_to "フォロワー", followers_user_path(@user.id)

- if current_user != @user
  - if @user.followed_by?(current_user)
    p = link_to "フォロー済み", user_relationships_path(@user.id), method: :delete
  - else
    p = link_to "フォローする", user_relationships_path(@user.id), method: :post

- @tweets.each do |tweet|
  hr
  p
    span ツイート内容:
    = link_to tweet.body, tweet_path(tweet.id)
- @favorite_tweets.each do |tweet|
  hr
  p
    span ファボツイート内容:
    = link_to tweet.body, tweet_path(tweet.id)